### ISSUE TITLE
Docs are lying about the use of PKCS#8

### ISSUE THREAD

**Issue by jonas-schievink** [dac-gmbh/gbl#9]
This is a PKCS#8 structure:
```
SEQUENCE (3 elem)
  INTEGER 0
  SEQUENCE (2 elem)
    OBJECT IDENTIFIER 1.2.840.10045.2.1 ecPublicKey (ANSI X9.62 public key type)
    OBJECT IDENTIFIER 1.2.840.10045.3.1.7 prime256v1 (ANSI X9.62 named elliptic curve)
  OCTET STRING (1 elem)
    SEQUENCE (3 elem)
      INTEGER 1
      OCTET STRING (32 byte) D5D8A5271B357B75410C6DBF795E081A2B6F4726BF8D1B67241728965E0A9A86
      [1] (1 elem)
        BIT STRING (520 bit) 0000010000101001010101010100110111000000110001101010111101101110101010…
```

This is what this library actually consumes:

```
SEQUENCE (4 elem)
  INTEGER 1
  OCTET STRING (32 byte) 2BEFAB605850DB0B3B8EF7E054D5C5FE639568B8CDFB869B45D0B0B3502CA3F5
  [0] (1 elem)
    OBJECT IDENTIFIER 1.2.840.10045.3.1.7 prime256v1 (ANSI X9.62 named elliptic curve)
  [1] (1 elem)
    BIT STRING (520 bit) 0000010011011100110001111010111111011101100100101110011111000010000010…
```

<sub>(these are test keys, don't worry)

**Comment by XAMPPRocky** [comment]
As far I can tell the function `P256KeyPair` calls [expects it to map to OpenSSL's `EC_KEY`](https://www.openssl.org/docs/man1.0.2/man3/i2d_ECPrivateKey.html) structure. The contents of this structure isn't documented, the only thing I could find on it is [this type definition](https://github.com/openssl/openssl/blob/f585cefc046409d04f26b73307e677625be26e5a/crypto/ec/ec_lcl.h#L280).

**Comment by jonas-schievink** [comment]
Yup, this is some "traditional format", but I don't know where exactly it's specified. It looks similar to what the `OCTET STRING` in the PKCS#8 encodes (the octet string itself contains DER-encoded data, apparently), but also includes the curve name.

**Comment by jonas-schievink** [comment]
Ah, it's an `ECPrivateKey` from [RFC 5915](https://tools.ietf.org/html/rfc5915):

```
   ECPrivateKey ::= SEQUENCE {
     version        INTEGER { ecPrivkeyVer1(1) } (ecPrivkeyVer1),
     privateKey     OCTET STRING,
     parameters [0] ECParameters {{ NamedCurve }} OPTIONAL,
     publicKey  [1] BIT STRING OPTIONAL
   }
```
